fix(pu): fix recompute advantage in on policy ppo and polish rnd_onppo algorithm
opendilab/DI-engine pull request #124
Opened 2021-11-18 11:13 UTC by puyuan1996

## Description
fix recompute advantage in on policy ppo, add onppo config for minigrid and mujoco env,
and polish rnd_onppo algorithm.

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2021-11-18 14:58 UTC, PaParaZz1 requested changes

2021-11-18 14:58 UTC, PaParaZz1 commented on dizoo/box2d/lunarlander/config/lunarlander_rnd_onppo_config.py
> +            #  self._traj_len  = max(1,64*8//8)=64
remove unused commented config item

2021-11-18 14:58 UTC, PaParaZz1 commented on ding/utils/default_helper.py
> +            elif k == 'logit':  # for continuous action
keep compatible, add new if-else branch in `isinstance(data[k], list) or isinstance(data[k], tuple)`

2021-11-18 14:58 UTC, PaParaZz1 commented on ding/reward_model/rnd_reward_model.py
> +        train_data = torch.clamp(train_data, min=-5, max=5)
add clamp min and max in rnd default_config

2021-11-18 14:58 UTC, PaParaZz1 commented on ding/reward_model/rnd_reward_model.py
> +        train_data = (train_data - to_tensor(self._running_mean_std_rnd_obs.mean).to(self.device)) / to_tensor(
add a obs_norm option

2021-11-18 14:58 UTC, PaParaZz1 commented on ding/reward_model/rnd_reward_model.py
> +        # self.clear_data()
why comment this line code

2021-11-18 14:58 UTC, PaParaZz1 commented on ding/reward_model/rnd_reward_model.py
> +        self._running_mean_std_rnd = RunningMeanStd(epsilon=1e-4)
rename to `self._running_mean_std_reward` and `self._running_mean_std_obs`

2021-11-18 14:58 UTC, PaParaZz1 commented on ding/reward_model/rnd_reward_model.py
> +                if item['reward'] > 0 and item['reward'] <= 1:
add a `extrinsic_reward_scale` option, defaults to 1.0

2021-11-18 14:58 UTC, PaParaZz1 commented on ding/policy/ppo.py
> +                torch.nn.utils.clip_grad_norm_(self._model.parameters(), 10)  # TODO(pu)
add `grad_clip` and `clip_value` option, defaults to False and 10

2021-11-18 14:58 UTC, PaParaZz1 commented on ding/policy/ppo.py
> +        self._unroll_len_add_burnin_step = self._unroll_len
remove burnin

2021-11-18 14:58 UTC, PaParaZz1 commented on ding/policy/ppo.py
> +    if not cfg.nstep_return:
use nstep_return as argument and replace if-else branch

2021-11-20 07:52 UTC, puyuan1996 commented on ding/reward_model/rnd_reward_model.py
> +        # self.clear_data()
在serial_pipeline_reward_model_onpolicy里面有设置
` if iter % cfg.reward_model.clear_buffer_per_iters == 0:
            reward_model.clear_data()`

2021-11-22 04:18 UTC, PaParaZz1 approved these changes

2021-11-22 04:35 UTC, merged