feature(zlx): envpool
opendilab/DI-engine pull request #228
Opened 2022-02-25 08:13 UTC by LuciusMos

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2022-03-15 06:10 UTC, PaParaZz1 requested changes

2022-03-15 06:10 UTC, PaParaZz1 commented on dizoo/atari/entry/envpool_dqn_main.py
> +from dizoo.atari.config.serial.pong.pong_dqn_config import pong_dqn_config
add `__init__.py` in `dizoo/atari/config/serial`

2022-03-16 16:21 UTC, LuciusMos commented on dizoo/atari/entry/envpool_dqn_main.py
> +import os
Preserve ``pong_dqn_envpool_main`` because envpool env manager is slightly different from others.

2022-03-16 16:22 UTC, LuciusMos commented on dizoo/atari/entry/envpool_dqn_main.py
> +    def ready_obs(self):
Fix this by changing collector

2022-03-17 13:19 UTC, PaParaZz1 approved these changes

2022-03-17 13:19 UTC, merged