WIP:  add WQMIX algorithm
opendilab/DI-engine pull request #24
Opened 2021-08-12 09:38 UTC by puyuan1996

add WQMIX algorithm.
You can run dizoo/smac/config/smac_3s5z_wqmix_config.py to validate related modules.

2021-08-12 10:28 UTC, PaParaZz1 commented on ding/model/template/wqmix.py
> +    def __init__(self, agent_num, state_dim, mixing_embed_dim):
写一下函数输入和输出参数的typing lint吧，参考已有的代码

2021-08-12 10:28 UTC, PaParaZz1 commented on ding/model/template/wqmix.py
> +        self.n_agents = agent_num
统一命名为agent_num吧

2021-08-12 10:28 UTC, PaParaZz1 commented on ding/model/template/wqmix.py
> +                remove it after forward
加一下`Q_star`的注释，解释一下这个键的意义

2021-08-12 10:28 UTC, PaParaZz1 commented on dizoo/smac/config/smac_3s5z_wqmix_config.py
> +        shared_memory=False,
`shared_memory`这个键应该是manager的，不应该出现在环境里啊

2021-08-13 02:29 UTC, puyuan1996 commented on dizoo/smac/config/smac_3s5z_wqmix_config.py
> +        shared_memory=False,
但好像qmix,coma他们的config里面，`shared_memory`这个键是在env里的。

2021-08-13 03:54 UTC, PaParaZz1 commented on dizoo/smac/config/smac_3s5z_wqmix_config.py
> +        shared_memory=False,
那是那边也写错了，一并修改吧

2021-08-13 06:18 UTC, puyuan1996 commented on dizoo/smac/config/smac_3s5z_wqmix_config.py
> +        shared_memory=False,
好的

2021-08-13 08:58 UTC, yifan123 commented on ding/model/template/wqmix.py
> +            mixer: bool = True,
wqmix算法感觉可以去掉mixer这个键，qmix加这个是为了包含vdn

2021-08-13 09:19 UTC, yifan123 commented on ding/policy/wqmix.py
> +        _loss, td_error_per_sample = v_1step_td_error(_data, self._gamma)
_loss后面不会被用到，建议直接写成_

2021-08-13 09:26 UTC, yifan123 commented on ding/policy/wqmix.py
> +        self._optimizer.zero_grad()
这里建议改成下面标准的先清空梯度，再backward，再step。
```
self._optimizer.zero_grad()
self._optimizer_star.zero_grad()

loss_weighted.backward(retain_graph=True)
loss_star.backward()

grad_norm = torch.nn.utils.clip_grad_norm_(list(self._model._q_network.parameters())+list(self._model._mixer.parameters()), self._cfg.learn.clip_value)
grad_norm = torch.nn.utils.clip_grad_norm_(list(self._model._q_network_star.parameters())+list(self._model._mixer_star.parameters()), self._cfg.learn.clip_value) # Q_star

self._optimizer.step()  # Q update
self._optimizer_star.step()  # Q_star update
```
第一次看的时候，以为之前的顺序安排是特意的，有些变量可能只能由一个loss更新，但仔细看不是的，所以建议写成标准形式，避免困惑

2021-08-13 09:28 UTC, yifan123 commented on ding/policy/wqmix.py
> +            target_total_q = self._learn_model.forward(next_inputs, single_step=False, Q_star=True)['total_q']
如果double_q=False, 这时候算出来的target_total_q使用的是Q_star的最优action，而不是Q_total的最优action,似乎是个bug

2021-08-13 12:40 UTC, puyuan1996 commented on ding/policy/wqmix.py
> +        self._optimizer.zero_grad()
好的

2021-09-09 05:40 UTC, PaParaZz1 requested changes

2021-09-09 05:40 UTC, PaParaZz1 commented on ding/model/template/wqmix.py
> +class Mixer_star(nn.Module):
Modify name, class name should use Big Hump Nomenclature (e.g.: `MixerStar`)

2021-09-09 05:40 UTC, PaParaZz1 commented on ding/model/template/wqmix.py
> +        if Q_star:  # forward using Q_star network
use lower case q

2021-09-09 05:40 UTC, PaParaZz1 commented on ding/model/template/wqmix.py
> +from typing import Union, List
add unittest with pytest like other models in this directory

2021-09-09 05:40 UTC, PaParaZz1 commented on ding/model/template/wqmix.py
> +class Mixer(nn.Module):
If this `Mixer` is the same as that in `qmix.py`, you should import it rather than implement it again

2021-09-09 05:40 UTC, PaParaZz1 commented on ding/model/template/wqmix.py
> +            - agent_qs (:obj:`torch.FloatTensor`): :math:`(B, N)`, where B is batch size and N is agent_num
I think it should be `(T, B, N)` for more clear comments

2021-09-09 05:40 UTC, PaParaZz1 commented on ding/model/template/wqmix.py
> +        self._global_state_encoder = nn.Sequential()
Why is this just a `nn.Sequential()`, and `_setup_global_encoder` method is never called

2021-09-09 05:40 UTC, PaParaZz1 commented on ding/policy/wqmix.py
> +class WQMIXPolicy(Policy):
This Policy should extends `QMIXPolicy` to reuse some methods

2021-09-09 05:40 UTC, PaParaZz1 commented on ding/policy/wqmix.py
> +        _data = v_1step_td_data(total_q, target_total_q, data['reward'], data['done'], data['weight'])
`data_` could be better

2021-09-09 05:40 UTC, PaParaZz1 commented on ding/policy/wqmix.py
> +            ws = torch.ones_like(td_error) * alpha_to_use
`torch.full_like` can be better, and it doesn't need additional multiply 1 in `torch.ones_like(td_error) * 1`

2021-09-09 05:40 UTC, PaParaZz1 commented on ding/policy/wqmix.py
> +        logit_detach = self._learn_model.forward(next_inputs, single_step=False, Q_star=False)['logit'].clone().detach()
`logit_detach` should name as `next_logit_detach`

2021-09-09 05:40 UTC, PaParaZz1 commented on ding/policy/wqmix.py
> +        grad_norm = torch.nn.utils.clip_grad_norm_(
You should name the return value of `clip_grad_norm_` separately for `q` and `q_star`, and visualize them separately too

2021-09-09 07:11 UTC, puyuan1996 commented on ding/model/template/wqmix.py
> +        self._global_state_encoder = nn.Sequential()
这里是借鉴qmix里面的写法，为了之后可扩展。现在好像是因为global_state本身已经比较紧凑，不用通过_setup_global_encoder里面的MLP做encoding

2021-09-09 07:13 UTC, puyuan1996 commented on ding/model/template/wqmix.py
> +        if Q_star:  # forward using Q_star network
ok. Thanks.

2021-09-10 08:11 UTC, PaParaZz1 commented on ding/model/template/tests/test_wqmix.py
> +    is_q_star = [True, False]
multi arguments in pytest can follow [this](https://github.com/opendilab/DI-engine/blob/main/ding/rl_utils/tests/test_ppo.py#L25)

2021-09-10 08:12 UTC, PaParaZz1 commented on ding/model/template/wqmix.py
> +        self._global_state_encoder = nn.Sequential()
OK and I find the same implementation in `qmix.py`, I understand what you mean and you can replace `nn.Sequential()` with `nn.Identity()`, which is more clear to users.

2021-09-28 09:38 UTC, PaParaZz1 approved these changes

2021-09-28 10:13 UTC, merged