config-polish-spaceinvaders
opendilab/DI-engine pull request #263
Opened 2022-04-03 02:33 UTC by kxzxvbk

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2022-04-03 12:10 UTC, PaParaZz1 requested changes

2022-04-03 12:10 UTC, PaParaZz1 commented on dizoo/atari/config/serial/spaceinvaders/spaceinvaders_a2c_config.py
> +    from ding.entry import serial_pipeline
a2c should use `serial_pipeline_onpolicy`

2022-04-03 12:10 UTC, PaParaZz1 commented on dizoo/atari/config/serial/spaceinvaders/c51_f1/config.py
>  from copy import deepcopy
remove `c51_f1` and `iqn_f1`

2022-04-03 12:10 UTC, PaParaZz1 commented on dizoo/atari/config/serial/spaceinvaders/spaceinvaders_dqfd_config.py
> +    config[0].policy.collect.demonstration_info_path = 'demonstration_info_path_placeholder'
`demonstration_info_path` should be `model_path`, please refer to our guideline

2022-04-03 12:11 UTC, PaParaZz1 commented
please modify PR's name according to our guideline

2022-04-06 07:22 UTC, puyuan1996 commented on dizoo/atari/config/serial/spaceinvaders/spaceinvaders_a2c_config.py
>  if __name__ == '__main__':
add line `# or you can enter ding -m serial_onpolicy -c spaceinvaders_a2c_config.py -s 0`.
其他config文件也需要加上启动命令这一行哈。不同算法使用了不同的serial_pipeline_X，启动命令对应使用 `ding -m serial_X`, 具体参考这里https://github.com/opendilab/DI-engine/blob/5d2beed4a8a07fb70599d910c6d53cf5157b133b/ding/entry/cli.py#L189

2022-04-06 07:22 UTC, puyuan1996 commented on dizoo/atari/config/serial/spaceinvaders/spaceinvaders_acer_config.py
> +if __name__ == '__main__':
add line `# or you can enter ding -m serial -c spaceinvaders_acer_config.py -s 0`

2022-04-08 05:29 UTC, kxzxvbk commented
现在还存在两个小问题：
1、gtrxl里面env_manager不能使用subprocess，只能使用base，否则会出现内存的错误。这点已经和Davide沟通过了；
2、PPG每个环境的entry不同，因此我只加上了运行的入口文件。

2022-04-11 08:49 UTC, puyuan1996 commented on dizoo/atari/config/serial/spaceinvaders/spaceinvaders_trex_dqn_config.py
> +    serial_pipeline_reward_model_trex([main_config, create_config], seed=0)
这里现在能正常运行吗？是不是也需要按照spaceinvaders_trex_offppo_config.py的形式修改一下呀？

2022-04-14 06:16 UTC, PaParaZz1 approved these changes

2022-04-14 06:16 UTC, merged