polish(pu): polish petting_zoo env and config
opendilab/DI-engine pull request #280
Opened 2022-04-13 01:44 UTC by puyuan1996

polish petting_zoo env to be compatiable with shared_memory=True case and polish petting_zoo config.

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2022-04-13 05:30 UTC, PaParaZz1 requested changes

2022-04-13 05:30 UTC, PaParaZz1 commented on dizoo/petting_zoo/config/ptz_simple_spread_atoc_config.py
> +        manager=dict(shared_memory=False, ),  # NOTE
why add shm and `NOTE` here

2022-04-13 05:30 UTC, PaParaZz1 commented on ding/envs/env_manager/subprocess_env_manager.py
> +            # for env multiagent_mujoco and petting_zoo
`# for multi_agent case, such as multiagent_mujoco and petting_zoo mpe` can be better

2022-04-13 08:37 UTC, puyuan1996 commented on dizoo/petting_zoo/config/ptz_simple_spread_atoc_config.py
> +        manager=dict(shared_memory=False, ),  # NOTE
这个config里面设置了agent_obs_only=True, obs与通常的不一样，现在改好了哈。

2022-04-13 08:38 UTC, puyuan1996 commented on ding/envs/env_manager/subprocess_env_manager.py
> +            # for env multiagent_mujoco and petting_zoo
好的

2022-04-14 05:00 UTC, Will-Nie commented on dizoo/petting_zoo/config/ptz_simple_spread_atoc_config.py
> +        manager=dict(shared_memory=False, ),  # NOTE
话说请问这个NOTE对应的解释被放在哪里了呢？

2022-04-14 05:49 UTC, PaParaZz1 approved these changes

2022-04-14 13:44 UTC, merged