feature(pu): add gfootball academy env and config
opendilab/DI-engine pull request #281
Opened 2022-04-13 04:42 UTC by puyuan1996

add gfootball academy env: academy_3_vs_1_with_keeper, academy_counterattack_hard,
and corresponding masac mappo config.

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2022-04-14 12:33 UTC, PaParaZz1 requested changes

2022-04-14 12:33 UTC, PaParaZz1 commented on ding/model/template/maqac.py
> +            agent_num: int,
remove this

2022-04-14 12:33 UTC, PaParaZz1 commented on dizoo/gfootball/config/gfootball_counter_mappo_config.py
> +        stop_value=0.99,
win rate 1

2022-04-14 12:33 UTC, PaParaZz1 commented on dizoo/gfootball/config/gfootball_counter_mappo_config.py
> +        # share_weight=True,
remove this comment

2022-04-14 12:33 UTC, PaParaZz1 commented on dizoo/gfootball/envs/gfootball_academy_env.py
> +"""The code below is adapted from https://github.com/lich14/CDS/tree/main/CDS_GRF/envs/grf"""
add unittest for this file

2022-04-14 12:33 UTC, PaParaZz1 commented on dizoo/gfootball/envs/gfootball_academy_env.py
> +from ding.envs import BaseEnv, BaseEnvTimestep, BaseEnvInfo
delete `BaseEnvInfo`, which is removed in main branch

2022-04-14 12:33 UTC, PaParaZz1 commented on dizoo/gfootball/envs/gfootball_academy_env.py
> +        if ball_loc[0] < 0 or any(ours_loc[:, 0] < 0):
add comment for this

2022-04-14 12:33 UTC, PaParaZz1 commented on dizoo/gfootball/envs/gfootball_academy_env.py
> +    def save_replay(self):
implement `save_replay` function

2022-04-14 12:33 UTC, PaParaZz1 commented on dizoo/gfootball/envs/gfootball_academy_env.py
> +    def create_collector_env_cfg(cfg: dict) -> List[dict]:
why add this method, `is_train` is not used in this file

2022-04-14 12:33 UTC, PaParaZz1 commented on dizoo/gfootball/envs/gfootball_academy_env.py
> +    def get_total_actions(self):
remove some methods like this, which is not used in this file now

2022-04-14 12:33 UTC, PaParaZz1 commented on dizoo/gfootball/envs/gfootball_academy_env.py
> +        if isinstance(actions, np.ndarray):
remove torch requirement, all the elements in env should be `np.array` and python native scalar

2022-04-14 12:33 UTC, PaParaZz1 commented on dizoo/gfootball/envs/gfootball_academy_env.py
> +        self._action_space = [gym.spaces.Discrete(self._env.action_space.nvec[1]) for _ in range(self.n_agents)]
update space like pettingzoo env

2022-04-14 12:55 UTC, puyuan1996 commented on ding/model/template/maqac.py
> +            agent_num: int,
这个是为了和mavac一致，之后如果not share parameters时会用到的

2022-04-14 12:57 UTC, puyuan1996 commented on dizoo/gfootball/envs/gfootball_academy_env.py
> +"""The code below is adapted from https://github.com/lich14/CDS/tree/main/CDS_GRF/envs/grf"""
好的

2022-04-14 13:00 UTC, puyuan1996 commented on dizoo/gfootball/envs/gfootball_academy_env.py
> +        if ball_loc[0] < 0 or any(ours_loc[:, 0] < 0):
好的

2022-04-14 13:44 UTC, PaParaZz1 commented on dizoo/gfootball/config/gfootball_counter_mappo_config.py
> +        # share_weight=True,
en

2022-04-14 13:44 UTC, PaParaZz1 commented on ding/model/template/maqac.py
> +            agent_num: int,
yes

2022-04-18 05:11 UTC, PaParaZz1 approved these changes

2022-04-18 05:11 UTC, merged