polish(lxl&zms): add middleware comments
opendilab/DI-engine pull request #317
Opened 2022-05-10 02:38 UTC by hiha3456

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2022-05-10 06:26 UTC, hiha3456 commented on ding/framework/middleware/collector.py
> +        - policy (:obj:`Policy`): The policy to be collected.
Here : Policy is ok I think

2022-05-10 06:33 UTC, hiha3456 commented on ding/framework/middleware/functional/collector.py
> +            - obs (:obj:`Dict[Tenosr]`): The input states fed into the model.
obs (:obj:`Dict[Tensor]`)

2022-05-10 06:38 UTC, hiha3456 commented on ding/framework/middleware/functional/collector.py
> +            - action: (:obj:`List[np.ndarray]`): The infered actions listed by env_id.
"inferred" actions

2022-05-10 06:48 UTC, hiha3456 commented on ding/framework/middleware/functional/evaluator.py
> +            - The evaluation will be executed if the task begins and enough train_iter after last evaluation.
Maybe "enough train_iter passed"?

2022-05-10 06:50 UTC, hiha3456 commented on ding/framework/middleware/functional/trainer.py
> +                It will trains only if the data is not empty.
It will train

2022-05-12 05:25 UTC, PaParaZz1 requested changes

2022-05-12 05:25 UTC, PaParaZz1 commented on ding/framework/middleware/ckpt_handler.py
> +            - eval_value (:obj:`int`): The eval reward of current iteration.
`eval_value` is not always int type, float can be more general.

2022-05-12 05:25 UTC, PaParaZz1 commented on ding/framework/middleware/ckpt_handler.py
> +            - train_iter (:obj:`int`): Number of train_iter.
Number of training iteration, i.e. the number of updating policy related network

2022-05-12 05:25 UTC, PaParaZz1 commented on ding/framework/middleware/collector.py
> +    """
move to `__init__` method, class comment should contain the whole overview and interface method list

2022-05-12 05:25 UTC, PaParaZz1 commented on ding/framework/middleware/collector.py
> +        - env (:obj:`BaseEnvManager`): The env for the collection.
add proper newline notation

2022-05-12 05:25 UTC, PaParaZz1 commented on ding/framework/middleware/functional/advantage_estimator.py
> +        Calculate value using observation of input data, then call function gae to get advantage. \
call function `gae`

2022-05-12 05:25 UTC, PaParaZz1 commented on ding/framework/middleware/functional/explorer.py
> +        The middleware that returns masked epsilon value.
add reason about why masks eps

2022-05-12 05:25 UTC, PaParaZz1 commented on ding/framework/middleware/learner.py
> +        - buffer_: The replay buffer to store the data for training.
no corresponding type

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/collector.py
> +        - transitions (:obj:`TransitionList`): The transition information which will be filled in this process.
Could be given more details about this transition information?

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/data_processor.py
> +            The float defines that, how many times of batch_size the size of data is \
remove 'that,'

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/data_processor.py
> +            The float defines that, how many times of batch_size the size of data is \
how many `batch_size` is the size of the data

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/data_processor.py
> +            which sampled from the corresponding buffer.\
which is sampled

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/data_processor.py
> +            - train_data (:obj:`Union[List[Dict], Dict[str, List[Dict]]]`): the fetched data. \
The fetched

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/data_processor.py
> +        And The return function is a generator which each time fetch a batch of data from the previous DataLoader.\
remove 'And'

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/data_processor.py
> +        The outer function transform a Pytorch Dataset to DataLoader. \
transforms

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/data_processor.py
> +        And The return function is a generator which each time fetch a batch of data from the previous DataLoader.\
fetches

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/data_processor.py
> +        - dataset (:obj:`Dataset`): The dataset of type torch.utils.data.Dataset which store the data.
stores

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/data_processor.py
> +        Save the expert data of offline RL in a path.
in a directory

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/data_processor.py
> +        Push trajectories into buffer in sqil learning pipeline.
the buffer

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/data_processor.py
> +        - expert (:obj:`bool`): Wether the pushed data is expert data or not. \
Whether

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/data_processor.py
> +            In each element of the pushed data, the reward will be set to one if this attribute is True, otherwise zero.
1 and 0

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/enhancer.py
> +        Estimate reward of train_data using reward_model.
the reward

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/enhancer.py
> +        Fetch a batch of data/a episode from buffer_, \
data/episode

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/enhancer.py
> +        - her_reward_model (:obj:`HerRewardModel`): Hindsight Experience Replay model which is used to process episodes.
Hindsight Experience Replay (HER). So that later is clear that HER refers to it

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/explorer.py
> +        The middleware that compute epsilon value according to the env_step.
computes

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/trainer.py
> +                It will trains only if the data is not empty.
'will train' or 'trains'

2022-05-12 07:29 UTC, davide97l commented on ding/framework/middleware/functional/trainer.py
> +                The log will be printed if it reachs certain values.
once it reaches

2022-05-13 11:23 UTC, PaParaZz1 approved these changes

2022-05-13 11:23 UTC, merged