feature(lisong): add sqil_sac example
opendilab/DI-engine pull request #374
Opened 2022-06-15 12:47 UTC by song2181

## Description
add sqil_sac example

## Related Issue
fix bug in sqilsac policy

## TODO

## Check List

- [x] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2022-06-16 08:04 UTC, PaParaZz1 requested changes

2022-06-16 08:04 UTC, PaParaZz1 commented on ding/example/sqil_sac.py
> +from dizoo.mujoco.config.hopper_sac_config import main_config as ex_main_config
use pendulum as demo env

2022-06-22 06:10 UTC, zjowowen commented on dizoo/classic_control/pendulum/config/pendulum_sqil_sac_config.py
> +    )
Please add a new empty line at the end of the file.
Usually, it would not pass the format test.

2022-06-22 06:41 UTC, zjowowen reviewed
This commit is a good implement of sqil-sac in new pipeline.
It would be better if expert model file be uploaded into a test folder so that we could run it directly, for most of the imitation learning algos.

2022-06-23 03:07 UTC, PaParaZz1 requested changes

2022-06-23 03:07 UTC, PaParaZz1 commented on ding/example/sqil.py
> +                cfg, expert_policy.collect_mode, expert_collector_env, cfg.policy.get('expert_random_collect_size', 0)
don't use `xxx.get` as much as possible

2022-06-23 03:07 UTC, PaParaZz1 commented on ding/example/sqil_sac.py
> +from ditk import logging
rename to `sqil_continuous.py`

2022-06-27 12:46 UTC, merged