feature(lxy): add sokoban env and config, with test TODO
opendilab/DI-engine pull request #397
Opened 2022-06-23 03:09 UTC by karroyan

## Description

## Related Issue

## TODO
test_sokoban_env.py

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2022-07-11 05:14 UTC, PaParaZz1 requested changes

2022-07-11 05:14 UTC, PaParaZz1 commented on dizoo/sokoban/envs/sokoban_env.py
> +import marshal
remove unused import

2022-07-11 05:14 UTC, PaParaZz1 commented on dizoo/sokoban/envs/test_sokoban_env.py
> +            #assert timestep.reward <= env.info().rew_space.value['max']
remove commented codes

2022-07-11 05:38 UTC, PaParaZz1 commented on dizoo/sokoban/envs/sokoban_env.py
> +import gym
add this env into [readme env list](https://github.com/opendilab/DI-engine#environment-versatility)

2022-07-11 10:57 UTC, karroyan commented on dizoo/sokoban/envs/sokoban_env.py
> +        obs, rew, done, info = self._env.step(int(action))
The input of _env.step should be int

2022-07-12 08:47 UTC, PaParaZz1 approved these changes

2022-07-12 08:47 UTC, merged