feature(wyh):PLR algorithm
opendilab/DI-engine pull request #408
Opened 2022-07-01 07:22 UTC by Weiyuhong-1998

## Description
PLR algorithm, including level replay, new pipeline

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2022-07-19 08:17 UTC, PaParaZz1 requested changes

2022-07-19 08:17 UTC, PaParaZz1 commented on ding/worker/level_replay/level_sampler.py
> +    def _score_transform(self, transform, temperature, scores):
only rank

2022-07-19 08:17 UTC, PaParaZz1 commented on ding/worker/level_replay/level_sampler.py
> +    def __init__(
add default config

2022-07-19 08:17 UTC, PaParaZz1 commented on ding/worker/level_replay/level_sampler.py
> +from collections import namedtuple
move this file to `ding/data/level_sampler.py`

2022-07-19 08:17 UTC, PaParaZz1 commented on ding/worker/level_replay/level_sampler.py
> +class LevelSampler():
add paper link in overview comment

2022-07-19 08:17 UTC, PaParaZz1 commented on ding/worker/level_replay/level_sampler.py
> +    def _init_seed_index(self, seeds):
merge these codes into `__init__`

2022-07-19 08:17 UTC, PaParaZz1 commented on ding/worker/level_replay/level_sampler.py
> +            score_function = self._average_gae
remove `average` prefix

2022-07-19 08:17 UTC, PaParaZz1 commented on ding/worker/level_replay/level_sampler.py
> +    def requires_value_buffers(self):
merge this property

2022-07-19 08:17 UTC, PaParaZz1 commented on ding/worker/collector/sample_serial_collector.py
> +    def collect_plr(
merge this method into collect, add level_seeds default argument

2022-07-19 08:17 UTC, PaParaZz1 commented on ding/entry/serial_entry_plr.py
> +        seeds[e] = seed
`seeds =  [level_sampler.sample('sequential') for _ in range(collector_env_num)]`

2022-07-19 08:17 UTC, PaParaZz1 commented on ding/entry/serial_entry_plr.py
> +    collector_env.seed(trans_seeds)
set seed, then reset env at once

2022-07-19 08:17 UTC, PaParaZz1 commented on ding/entry/serial_entry_plr.py
> +        if collector.envstep >= max_env_step or learner.train_iter >= max_train_iter:
move these two lines to the end of this while loop

2022-07-19 08:17 UTC, PaParaZz1 commented on ding/entry/serial_entry_plr.py
> +        train_data_2 = default_preprocess_learn(new_data, ignore_done=cfg.policy.learn.ignore_done, use_nstep=False)
rename to stacked_data

2022-07-19 08:17 UTC, PaParaZz1 commented on ding/worker/level_replay/level_sampler.py
> +                if not start_t < total_steps: break
break should occupy a solo line

2022-07-19 08:18 UTC, PaParaZz1 commented on ding/entry/serial_entry_plr.py
> +import logging
add PLR into readme

2022-07-28 04:45 UTC, zerlinwang commented
lastly, use yapf and flake8 to standardise code style, and check the failed unit_test

2022-07-29 15:59 UTC, PaParaZz1 requested changes

2022-07-29 15:59 UTC, PaParaZz1 commented on ding/worker/collector/sample_serial_collector.py
> +            level_seeds: Optional[List] = None,
add comment for this argument

2022-07-29 15:59 UTC, PaParaZz1 commented on dizoo/procgen/entry/bigfish_plr_config.py
> +        level_replay_strategy='min_margin',
maybe we can omit `level_replay` prefix

2022-07-29 15:59 UTC, PaParaZz1 commented on ding/entry/serial_entry_plr.py
> +    level_seeds = torch.Tensor(seeds)
add comment for why transform into tensor

2022-07-29 15:59 UTC, PaParaZz1 commented on ding/data/level_replay/level_sampler.py
> +        #returns = kwargs['returns']
remove commented code

2022-07-29 15:59 UTC, PaParaZz1 commented on ding/data/level_replay/level_sampler.py
> +    def _score_transform(self, transform, temperature, scores):
add all python typing

2022-07-29 15:59 UTC, PaParaZz1 commented on ding/data/level_replay/level_sampler.py
> +            seed_idx = np.random.choice(range((len(self.seeds))))
range(len(self.seeds))

2022-07-29 15:59 UTC, PaParaZz1 commented on ding/data/level_replay/level_sampler.py
> +            return int(seed)
why int here

2022-07-29 15:59 UTC, PaParaZz1 commented on ding/data/level_replay/level_sampler.py
> +                if np.random.rand() > self.nu or not proportion_seen < 1.0:
np.isclose(proportion_seen, 1.0)?

2022-07-29 15:59 UTC, PaParaZz1 commented on ding/data/level_replay/level_sampler.py
> +            self.seed_staleness = self.seed_staleness + 1
+= 1

2022-07-29 15:59 UTC, PaParaZz1 commented on ding/data/level_replay/level_sampler.py
> +                    score_function_kwargs['value_preds'] = value[start_t:t, actor_index]
use our rename method rather than something like `value_preds`

2022-07-29 15:59 UTC, PaParaZz1 commented on ding/data/level_replay/level_sampler.py
> +        return advantages.abs().mean().item()
why abs here, add some comments about motivation

2022-07-29 15:59 UTC, PaParaZz1 commented on ding/data/level_replay/level_sampler.py
> +            raise ValueError(f'Unsupported strategy, {self.strategy}')
use our format, like `'Not supported strategy: {}'.format(self.strategy)`

2022-07-29 15:59 UTC, PaParaZz1 commented on ding/data/level_replay/level_sampler.py
> +    def seed_range(self):
where is this method used

2022-07-29 15:59 UTC, PaParaZz1 commented on ding/data/level_replay/level_sampler.py
> +        temperature: float = 1.0,
add this arguments to config

2022-08-01 06:14 UTC, Weiyuhong-1998 commented on ding/data/level_replay/level_sampler.py
> +            return int(seed)
seed must be int data

2022-08-02 03:09 UTC, PaParaZz1 approved these changes

2022-08-02 03:09 UTC, merged