feature(pu): add il and rl demo for gfootball
opendilab/DI-engine pull request #418
Opened 2022-07-19 04:51 UTC by puyuan1996

## Description
- adapt gfootball env to DI-engine env interface.
- add gfootball imitation learning config, use the rule_based_bot and kaggle_5th_place model to collect demo data.
- add episode_to_transitions_filter to only use the demo data whose return is larger than a given threshold in il demo.
- add dqn config for gfootball.

## Related Issue

https://github.com/opendilab/DI-engine/issues/335

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2022-07-19 06:09 UTC, PaParaZz1 requested changes

2022-07-19 06:09 UTC, PaParaZz1 commented on dizoo/gfootball/entry/gfootball_dqn_config.py
> +        eval=dict(evaluator=dict(eval_freq=5000, n_episode=evaluator_env_num)),
why `n_episode` here

2022-07-19 06:09 UTC, PaParaZz1 commented on dizoo/gfootball/entry/gfootball_il_config.py
> +        nstep=1,
remove unused key like `nstep`

2022-07-19 06:09 UTC, PaParaZz1 commented on dizoo/gfootball/entry/gfootball_il_config.py
> +            learner=dict(load_path=None),
remove this

2022-07-19 06:09 UTC, PaParaZz1 commented on dizoo/gfootball/entry/gfootball_il_kaggle5th_main.py
> +create_cfg.policy.type = create_cfg.policy.type + '_command'
remove codes not used here, such as `command`

2022-07-19 06:09 UTC, PaParaZz1 commented on dizoo/gfootball/model/bots/TamakEriFever/football_ikki.py
> +            p = torch.cat([p, x['distance']['p2bo'].repeat(1,2,1).view(bs, p.size(1), -1), s_concat], dim=2)
correct format

2022-07-19 06:09 UTC, PaParaZz1 commented on dizoo/gfootball/model/q_network/football_q_network_default_config.yaml
>                  output_dim: 1
if yaml is not used, remove it

2022-07-19 06:09 UTC, PaParaZz1 commented on dizoo/gfootball/model/q_network/football_q_network.py
> +with open(os.path.join(os.path.dirname(__file__), 'football_q_network_default_config.yaml')) as f:
why not use python config, which has been already implemented

2022-07-19 06:09 UTC, PaParaZz1 commented on dizoo/gfootball/model/q_network/football_q_network.py
> +        r"""
remove DRQN related comment if you have updated them for football

2022-07-19 06:09 UTC, PaParaZz1 commented on dizoo/gfootball/model/q_network/football_q_network.py
> +class FootballNGU(nn.Module):
remove ngu code in remote repo

2022-07-19 06:36 UTC, PaParaZz1 commented on ding/policy/football_bc.py
> +from typing import Tuple, List, Dict, Any
move football bc to dizoo

2022-07-19 08:02 UTC, puyuan1996 commented on ding/entry/serial_entry_bc.py
> +    if not cont and cfg.policy.learn.show_accuracy:
这里是为了训练完成后，测试训练好的模型在整个数据集上的准确率，由于是将总数据集分成很多个小的minibatch进行测试，然后求平均得到整个训练集的准确率，好像只能写在训练循环外面？

2022-07-20 06:01 UTC, PaParaZz1 requested changes

2022-07-20 06:15 UTC, puyuan1996 commented on dizoo/gfootball/entry/gfootball_il_config.py
> +create_config = gfootball_il_create_config
由于有收集样本，训练，测试的3个阶段，是写在了同目录下的 x_main.py里面

2022-07-20 06:18 UTC, puyuan1996 commented on dizoo/gfootball/entry/gfootball_dqn_config.py
> +    env_manager=dict(type='base'),
gfootball obs 包括 {processed_obs'':X,  'raw_obs',X}结构比较复杂，目前还是没有适配好subprocess, 之后我再试试

2022-07-20 06:19 UTC, puyuan1996 commented on ding/policy/bc.py
> +                self.action_accuracy_in_dataset = {k: [] for k in range(19)}
ok, changed

2022-07-20 06:35 UTC, PaParaZz1 commented on dizoo/gfootball/entry/gfootball_il_config.py
> +create_config = gfootball_il_create_config
add some comments to give guidance

2022-07-20 06:35 UTC, PaParaZz1 commented on dizoo/gfootball/entry/gfootball_dqn_config.py
> +    env_manager=dict(type='base'),
try subprocess with `shared_memory=False`?

2022-07-20 07:21 UTC, PaParaZz1 requested changes

2022-07-20 07:21 UTC, PaParaZz1 commented on ding/policy/bc.py
> +        if not hasattr(self._cfg.learn, 'weight_decay') or self._cfg.learn.weight_decay is None:
don't use hasttr, you have added it into default_config

2022-07-20 07:21 UTC, PaParaZz1 commented on dizoo/gfootball/model/q_network/tests/test_config.py
> +import pytest
remove this

2022-07-20 07:21 UTC, PaParaZz1 commented on dizoo/gfootball/model/q_network/tests/test_football_model.py
> +with open(os.path.join(os.path.abspath(os.path.dirname(os.path.dirname(__file__))),
move to python config

2022-07-20 08:17 UTC, puyuan1996 commented on dizoo/gfootball/entry/gfootball_dqn_config.py
> +    env_manager=dict(type='base'),
ok, thanks

2022-07-20 08:27 UTC, puyuan1996 commented on dizoo/gfootball/entry/gfootball_il_config.py
> +create_config = gfootball_il_create_config
ok

2022-07-20 08:31 UTC, puyuan1996 commented on ding/policy/bc.py
> +        if not hasattr(self._cfg.learn, 'weight_decay') or self._cfg.learn.weight_decay is None:
ok, thanks

2022-07-20 08:55 UTC, PaParaZz1 commented on dizoo/gfootball/entry/gfootball_il_kaggle5th_main.py
> +from copy import deepcopy
rename il to bc

2022-07-20 09:17 UTC, puyuan1996 commented on ding/policy/bc.py
> +        if not hasattr(self._cfg.learn, 'weight_decay') or self._cfg.learn.weight_decay is None:
在https://github.com/opendilab/DI-engine/blob/1fae1d177fe6f87e104d39df69003344f8588fe2/ding/entry/tests/test_serial_entry_bc.py#L137 这里如果去掉hasattr(self._cfg.learn, 'weight_decay')会出错，好像是dqn_bc这样的策略不能继承bc默认的config?

2022-07-20 09:27 UTC, puyuan1996 commented on dizoo/gfootball/entry/gfootball_il_kaggle5th_main.py
> +from copy import deepcopy
ok

2022-07-20 10:53 UTC, PaParaZz1 commented on ding/policy/bc.py
> +        if not hasattr(self._cfg.learn, 'weight_decay') or self._cfg.learn.weight_decay is None:
modify dqn_bc like [this](https://github.com/opendilab/DI-engine/blob/main/ding/world_model/base_world_model.py#L63)

2022-07-20 10:54 UTC, PaParaZz1 commented on dizoo/gfootball/entry/show_dataset.py
> +    create_cfg.policy.type = create_cfg.policy.type + '_command'
command

2022-07-20 10:57 UTC, PaParaZz1 approved these changes

2022-07-20 12:08 UTC, merged