feature(rjy): add rocket env
opendilab/DI-engine pull request #449
Opened 2022-08-19 06:48 UTC by nighood

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2022-08-19 12:26 UTC, puyuan1996 commented on dizoo/rocket/envs/rocket_env.py
> +            # if hasattr(self._cfg, 'obs_plus_prev_action_reward') and self._cfg.obs_plus_prev_action_reward:
这是ngu算法相关的，这里用不到，直接删除了哈

2022-08-19 12:26 UTC, puyuan1996 commented on dizoo/rocket/envs/rocket_env.py
> +        # self._path_to_bg_img = self._cfg.path_to_bg_img
无用的注释删除掉

2022-08-19 12:27 UTC, puyuan1996 commented on dizoo/rocket/envs/rocket_env.py
> +        # obs = [item[key] for item in obs for key in item]   # NOTE(rjy): here obs is a dict, we just need its values
这里也是直接删除

2022-08-19 12:32 UTC, puyuan1996 commented on dizoo/rocket/envs/rocket_env.py
> +from typing import Any, List, Union, Optional
在DI-engine目录下执行`bash format.sh ding dizoo/rocket` 对你添加的代码进行格式化，并且用`flake8 dizoo/rocket`进行格式检查，按照提示改正格式
![image](https://user-images.githubusercontent.com/48008469/185618810-609cb131-1668-47be-b631-8ab6a1e389ae.png)

2022-08-19 12:34 UTC, puyuan1996 commented on dizoo/rocket/envs/rocket_env.py
> +        rew = to_ndarray([rew]).astype(np.float32)  # wrapped to be transfered to a array with shape (1,)
`# xxx`注释一般添加在 待说明代码 的上方

2022-08-19 12:35 UTC, puyuan1996 commented on dizoo/rocket/entry/rocket_ppo_main_nseed_cuda.py
> +from turtle import Terminator
这个文件直接删除，config中默认设置`cuda=True`

2022-08-19 12:36 UTC, puyuan1996 commented on dizoo/rocket/config/rocket_ppo_config.py
> +    exp_name='rocket_onppo_seed0',
`exp_name='rocket_hover_onppo_seed0',`

2022-08-19 12:42 UTC, puyuan1996 commented on ding/framework/middleware/functional/advantage_estimator.py
> +            #     data.obs = to_device(data.obs, 'cuda:0')
删除这里多余的代码

2022-08-25 02:21 UTC, Cloud-Pku requested changes

2022-09-02 04:38 UTC, PaParaZz1 approved these changes

2022-09-02 04:39 UTC, merged