feature(rjy): add rule-based gomoku expert action
opendilab/DI-engine pull request #465
Opened 2022-09-01 18:57 UTC by nighood

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2022-09-02 07:59 UTC, PaParaZz1 requested changes

2022-09-02 07:59 UTC, PaParaZz1 commented on dizoo/board_games/gomoku/envs/gomoku_expert.py
> +        # 同一色棋子的权重
use English comment

2022-09-02 07:59 UTC, PaParaZz1 commented on dizoo/board_games/gomoku/envs/gomoku_expert.py
> +# encoding: utf-8
add unittest

2022-09-09 07:33 UTC, puyuan1996 commented on dizoo/board_games/gomoku/envs/test_gomoku_expert_action.py
> +def test_naive():
参考[这里](https://github.com/opendilab/DIengine/blob/main/dizoo/board_games/tictactoe/envs/test_tictactoe_expert_action.py#L6)，写成pytest的形式

2022-09-09 07:33 UTC, puyuan1996 commented on dizoo/board_games/gomoku/envs/gomoku_env.py
> +        return self.expert.get_move(obs)
为了与其他棋类环境一致，命名中统一把move换成action吧？

2022-09-09 07:33 UTC, puyuan1996 commented on dizoo/board_games/gomoku/envs/gomoku_expert.py
> +    def scan_leftright(self, i, j, player):
仿照[这里](https://github.com/opendilab/DI-engine/blob/main/ding/model/common/head.py)，为每个method添加标准格式的注释

2022-09-09 07:33 UTC, puyuan1996 commented on dizoo/board_games/gomoku/envs/gomoku_expert.py
> +        self.max_value = 10012345
这里获得专家动作为什么要用到max_value的概念呢，可以在类名下面写一个overview的整体思路介绍哈，还有里面的一些数值
<img width="467" alt="image" src="https://user-images.githubusercontent.com/48008469/189296409-8a83c3df-1d33-43a3-a068-86e0b4fce4af.png">
应该是与棋盘大小相关的吧？可能需要传入board_size自适应的确定这些值

2022-09-09 07:33 UTC, puyuan1996 commented on dizoo/board_games/gomoku/envs/gomoku_expert.py
> +            # Indicates that one direction can already be rushed to 4
英文注释不一定直译，解释清楚原理即可，例如这里 `rushed to 4` 就不好理解，其他的英文注释也需要修改一下

2022-09-15 13:49 UTC, nighood commented on dizoo/board_games/gomoku/envs/test_gomoku_expert_action.py
> +def test_naive():
This link is dead?

2022-09-21 08:06 UTC, PaParaZz1 approved these changes

2022-09-21 08:10 UTC, merged