update entry
opendilab/DI-engine pull request #525
Opened 2022-10-27 13:07 UTC by kxzxvbk

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2022-10-30 15:14 UTC, puyuan1996 commented on dizoo/procgen/entry/coinrun_ppo_main.py
> +    evaluator_env = BaseEnvManager(env_fn=[lambda: wrapped_procgen_env(coinrun_ppo_default_config.env) for _ in range(evaluator_env_num)],
使用`partial(wrapped_procgen_env, cfg=coinrun_ppo_default_config.env)`？

2022-10-30 15:14 UTC, puyuan1996 commented on dizoo/procgen/entry/coinrun_ppo_main.py
> +from dizoo.procgen.config.coinrun_ppo_config import coinrun_ppo_default_config
参考我们之前的[config规范](https://di-engine-docs.readthedocs.io/zh_CN/latest/20_spec/config_spec_zh.html#id4) `coinrun_ppo_default_config` procgen/config里面的default全部去掉？

2022-10-30 15:14 UTC, puyuan1996 commented on dizoo/dmc2gym/entry/ppo_main.py
> +from ding.worker import BaseLearner, SampleSerialCollector, InteractionSerialEvaluator
文件命名为`dmc2gym_onppo_main.py`

2022-10-30 15:14 UTC, puyuan1996 commented on dizoo/dmc2gym/entry/ppo_main.py
> +    evaluator_env = BaseEnvManager(env_fn=[lambda: wrapped_dmc2gym_env(cartpole_balance_ppo_config.env) for _ in range(evaluator_env_num)],
使用`partial(wrapped_dmc2gym_env, cfg=cartpole_balance_ppo_config.env)`？

2022-10-30 15:14 UTC, puyuan1996 commented on dizoo/dmc2gym/entry/ppo_main.py
> +    # collector_env = BaseEnvManager(env_fn=[lambda: DMC2GymEnv(cfg.env) for _ in range(collector_env_num)],
去掉？

2022-10-30 15:14 UTC, puyuan1996 commented on dizoo/rocket/entry/new_hover.py
> +from turtle import Terminator
命名为`rocket_hover_onppo_main_v2`?

2022-10-31 13:53 UTC, PaParaZz1 requested changes

2022-10-31 13:53 UTC, PaParaZz1 commented on dizoo/dmc2gym/config/dmc2gym_ppo_config.py
> +create_config = cartpole_balance_create_config
add comments for which entry file can be called to use this config

2022-10-31 13:53 UTC, PaParaZz1 commented on dizoo/dmc2gym/entry/dmc2gym_onppo_main.py
> +        self._observation_space = dmc2gym_env_info[cfg.domain_name][cfg.task_name]["observation_space"](
reuse varaible `dmc2gym_env_info[cfg.domain_name][cfg.task_name]`

2022-10-31 13:53 UTC, PaParaZz1 commented on dizoo/dmc2gym/entry/dmc2gym_onppo_main.py
> +    def seed(self, seed: int, dynamic_seed: bool = True) -> None:
why add this method, is it added in `DingEnvWrapper`?

2022-10-31 13:53 UTC, PaParaZz1 commented on dizoo/dmc2gym/entry/dmc2gym_onppo_main.py
> +class InfoWrapper(gym.Wrapper):
why name this class `InfoWrapper`

2022-10-31 13:53 UTC, PaParaZz1 commented on dizoo/dmc2gym/entry/dmc2gym_onppo_main.py
> +def main(cfg, seed=0, max_iterations=int(1e10)):
don't use `max_iterations` argument but set `max_env_step` like that in `serial_pipeline`

2022-11-15 05:02 UTC, PaParaZz1 approved these changes

2022-11-15 05:03 UTC, merged