feature(zjow): impala policy for continuous action space
opendilab/DI-engine pull request #551
Opened 2022-12-02 06:10 UTC by zjowowen

Add impala policy for continuous action space.
Support action reparameterized by dimension-wise independent gaussian disribution.

2022-12-04 11:48 UTC, PaParaZz1 requested changes

2022-12-04 11:48 UTC, PaParaZz1 commented on ding/policy/impala.py
> +        else:
add assertion in the beginning of policy (init method), then you don't need to raise the error in following implementations.

2022-12-04 11:48 UTC, PaParaZz1 commented on ding/rl_utils/isw.py
> +    target_output, behaviour_output, action, action_space_type: str = 'discrete', requires_grad: bool = False
add typing for other arguments

2022-12-06 07:13 UTC, PaParaZz1 approved these changes

2022-12-07 03:41 UTC, zjowowen commented
**bipedalwalker-v3 by impala policy**

![image](https://user-images.githubusercontent.com/93968541/206082328-67c59f8c-e56f-4e0f-9d88-5c3477649779.png)

2022-12-07 03:50 UTC, merged