add carracing in box2d
opendilab/DI-engine pull request #575
Opened 2023-02-03 15:22 UTC by Super1ce

Add CarRacing env and config of DQN

2023-02-07 02:40 UTC, puyuan1996 commented on dizoo/box2d/carracing/config/__init__.py
> +from .carracing_dqn_config import carracing_dqn_config, carracing_dqn_create_config
执行 bash format.sh dizoo/box2d/carracing 格式化文件

2023-02-07 02:40 UTC, puyuan1996 commented on dizoo/box2d/carracing/envs/carracing_env.py
> +        return "DI-engine LunarLander Env"
CarRacing

2023-02-07 02:40 UTC, puyuan1996 commented on dizoo/box2d/carracing/envs/test_carracing_env.py
> +            'env_id': 'CarRacingContinuous-v1',
为什么这里是v1, 其他文件是v2?

2023-02-07 02:40 UTC, puyuan1996 commented on dizoo/box2d/carracing/envs/carracing_env.py
> +        obs = obs.astype(np.float32) / 255
/255是必须的吗？如果不除会报错吗？或许可以加一个option选择是否除以255

2023-02-07 02:40 UTC, puyuan1996 commented on dizoo/box2d/carracing/config/carracing_dqn_config.py
> +    # env_manager=dict(type='base'),
没有用到的注释可以去掉

2023-02-07 02:40 UTC, puyuan1996 commented on dizoo/box2d/carracing/config/carracing_dqn_config.py
> +    # or you can enter `ding -m serial -c lunarlander_dqn_config.py -s 0`
carraciing_dqn*

2023-02-07 02:40 UTC, puyuan1996 commented on dizoo/box2d/carracing/config/carracing_dqn_config.py
> +        load_path="./carracing_seed0/ckpt/ckpt_best.pth.tar",
load_path这里没有用到，可以删除了

2023-02-07 02:44 UTC, puyuan1996 commented on dizoo/box2d/carracing/config/__init__.py
> +from .carracing_dqn_config import carracing_dqn_config, carracing_dqn_create_config
commit的信息，也按照规范哈，类似这样 `feature(zc): add carring_env and related dqn config.`

2023-02-08 05:25 UTC, PaParaZz1 requested changes

2023-02-08 05:25 UTC, PaParaZz1 commented on dizoo/box2d/carracing/config/carracing_dqn_config.py
> +        # Whether to use shared memory. Only effective if "env_manager_type" is 'subprocess'
why add these two line comments

2023-02-08 05:25 UTC, PaParaZz1 commented on dizoo/box2d/carracing/envs/carracing_env.py
> +import cv2
参考[文档](https://github.com/opendilab/DI-engine-docs/blob/main/source/21_code_style/index_zh.rst#%E5%90%88%E7%90%86%E7%9A%84-import-%E9%A1%BA%E5%BA%8F)修正import顺序

2023-02-08 05:25 UTC, PaParaZz1 commented on dizoo/box2d/carracing/envs/test_carracing_env.py
> +            assert timestep.obs.shape == (96, 96, 3)
the shape should be (3, 96, 96)

2023-02-08 05:26 UTC, PaParaZz1 commented
add the information of this env in [env table](https://github.com/opendilab/DI-engine#environment-versatility)

2023-02-08 10:04 UTC, PaParaZz1 requested changes

2023-02-08 10:04 UTC, PaParaZz1 commented on dizoo/box2d/carracing/config/carracing_dqn_config.py
> +    exp_name='carracing_dqn_seed0-withouconfig',
polish exp_name

2023-02-08 10:06 UTC, PaParaZz1 requested changes

2023-02-08 10:06 UTC, PaParaZz1 commented on dizoo/box2d/carracing/envs/carracing_env.py
> +        if 'Continuous' in self._env_id:
remove `Continuous` related codes, which is abandoned in latest gym

2023-02-08 10:06 UTC, PaParaZz1 commented on dizoo/box2d/carracing/envs/carracing_env.py
> +                low=np.min(self._env.observation_space.low),
correct range (after dividing 255)

2023-02-08 10:06 UTC, PaParaZz1 commented on dizoo/box2d/carracing/envs/carracing_env.py
> +            if hasattr(self._cfg, 'obs_plus_prev_action_reward') and self._cfg.obs_plus_prev_action_reward:
remove this wrapper, it is only used in some special cases.

2023-02-08 12:24 UTC, PaParaZz1 approved these changes

2023-02-09 03:23 UTC, merged