feature(zp): add Dreamerv3 features
opendilab/DI-engine pull request #652
Opened 2023-04-25 06:55 UTC by zhangpaipai

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2023-06-02 05:58 UTC, PaParaZz1 requested changes

2023-06-02 05:58 UTC, PaParaZz1 commented on ding/world_model/utils.py
> +def weight_init(m):
add usage comments about this init function

2023-06-02 05:58 UTC, PaParaZz1 commented on ding/world_model/utils.py
> +class ContDist:
polish all the class name of distributions we implemented, unify their name format

2023-06-02 05:58 UTC, PaParaZz1 commented on ding/world_model/utils.py
> +        elif self._agg == 'sum':
maybe we can polish the related variable name and make them more readable, such as `agg` to `aggregation`

2023-06-02 05:58 UTC, PaParaZz1 commented on ding/world_model/utils.py
> +    def __init__(self, mode, dist='mse', agg='sum', tol=1e-8, dim_to_reduce=[-1, -2, -3]):
add python typing lint

2023-06-02 05:58 UTC, PaParaZz1 commented on ding/world_model/utils.py
> +def symlog(x):
move this two functions to `ding/rl_utils/value_rescale.py`

2023-06-02 05:58 UTC, PaParaZz1 commented on ding/world_model/utils.py
> +    @property
why add this method

2023-06-02 05:58 UTC, PaParaZz1 commented on ding/world_model/utils.py
> +    def __getattr__(self, name):
why overwrite this method here

2023-06-02 05:58 UTC, PaParaZz1 commented on ding/world_model/utils.py
> +        print("mean called")
remove debug print

2023-06-02 05:58 UTC, PaParaZz1 commented on ding/world_model/utils.py
> +        return _mode.detach() + self._dist.mean - self._dist.mean.detach()
why use detach here

2023-06-02 05:58 UTC, PaParaZz1 commented on ding/world_model/model/networks.py
> +        if self._dist == "huber":
elif here

2023-06-02 05:58 UTC, PaParaZz1 commented on ding/model/common/tests/test_encoder.py
> +a.test_dreamer_conv_encoder()
why add these two lines

2023-06-02 05:58 UTC, PaParaZz1 commented on ding/model/common/encoder.py
> +class DreamerLayerNorm(nn.Module):
move these two classes to `ding/torch_utils/network`

2023-06-02 05:58 UTC, PaParaZz1 commented on ding/model/common/encoder.py
> +        if len(self.hidden_size_list) >= len(kernel_size) + 2:
format codes with with a maximum of 120 characters per line

2023-06-02 06:01 UTC, zjowowen commented on ding/model/common/encoder.py
> +        self.output_size = hidden_size_list[-1]  # outside to use
"# outside to use" remove comment

2023-06-02 06:03 UTC, zjowowen commented on ding/model/common/encoder.py
> +        return max((math.ceil(i / s) - 1) * s + (k - 1) * d + 1 - i, 0)
Add data type for i,k,s,d
Add function notation

2023-06-02 06:03 UTC, zjowowen commented on ding/model/common/encoder.py
> +        super(DreamerLayerNorm, self).__init__()
Add data type

2023-06-02 06:05 UTC, zjowowen commented on ding/world_model/model/networks.py
> +        inp_dim,  # config.dyn_stoch * config.dyn_discrete + config.dyn_deter
remove " # config.dyn_stoch * config.dyn_discrete + config.dyn_deter"?

2023-06-02 06:05 UTC, zjowowen commented on ding/world_model/model/networks.py
> +class DenseHead(nn.Module):
Tell some information about this class.

2023-06-02 06:07 UTC, zjowowen commented on ding/world_model/model/networks.py
> +    def forward(self, features, dtype=None):
what's the use of dtype?
I can not find where it is used?

2023-06-02 06:09 UTC, zjowowen commented on ding/world_model/model/networks.py
> +    def forward(self, features, dtype=None):
I think model module should take one input for forward function.

2023-06-02 06:12 UTC, zjowowen commented on ding/world_model/model/networks.py
> +            std = self.std_layer(out)
please make sure the std_layer output is always non-negative.
I am afraid there would be dangerous by using only nn.Linear

2023-06-02 06:14 UTC, zjowowen commented on ding/world_model/model/networks.py
> +from torch import distributions as torchd
please do not use torchd as short module name. It's not a standard coding format.
It's better to from torch.distributions import XXXXX.
Import only what you need.

2023-06-02 06:19 UTC, zjowowen commented on ding/world_model/utils.py
> +class OneHotDist(torchd.one_hot_categorical.OneHotCategorical):
Add class notation

2023-06-02 06:20 UTC, zjowowen commented on ding/world_model/utils.py
> +class SampleDist:
Add class notation

2023-06-02 06:24 UTC, zjowowen commented on ding/world_model/utils.py
> +class SampleDist:
Why this class is needed? It seems do not contain any useful information?
You can just rewrite these methods into single line code.

2023-06-02 06:26 UTC, zjowowen commented on ding/world_model/utils.py
> +class TwoHotDistSymlog():
Add class and function notations

2023-06-02 06:28 UTC, zjowowen commented on ding/world_model/utils.py
> +    def __init__(self, logits=None, low=-20.0, high=20.0, device='cpu'):
device is set by default. It should not  be explicitly set by some argument.

2023-06-02 06:29 UTC, zjowowen commented on ding/world_model/utils.py
> +class Bernoulli:
Add class notation

2023-06-02 06:31 UTC, zjowowen commented on ding/world_model/utils.py
> +class UnnormalizedHuber(torchd.normal.Normal):
Add notation

2023-08-07 09:06 UTC, PaParaZz1 approved these changes

2023-08-07 09:08 UTC, merged