refactor(lyd): refactor dt_policy in new pipeline and add img input support
opendilab/DI-engine pull request #693
Opened 2023-07-25 09:31 UTC by AltmanD

Refactor DT to new pipeline.
Add img input support for atari.

2023-07-25 14:49 UTC, PaParaZz1 requested changes

2023-07-25 14:49 UTC, PaParaZz1 commented on ding/policy/dt.py
> +        self.max_env_score = -1.0
remove this

2023-07-25 14:49 UTC, PaParaZz1 commented on ding/policy/dt.py
> +        torch.nn.utils.clip_grad_norm_(self._learn_model.parameters(), 0.25)
add this argument (0.25) into config

2023-07-31 05:31 UTC, AltmanD commented on dizoo/d4rl/config/__init__.py
> +# from .hopper_medium_cql_config import hopper_medium_cql_config
configs these want import are not exist

2023-07-31 12:33 UTC, PaParaZz1 requested changes

2023-07-31 12:33 UTC, PaParaZz1 commented on ding/policy/dt.py
> +        rtg_scale=1000,  # normalize returns to go
add comments for each parameters in default config

2023-07-31 12:33 UTC, PaParaZz1 commented on ding/policy/dt.py
> +        if not self._cfg.model.continuous:
reverse if-else branch

2023-07-31 12:33 UTC, PaParaZz1 commented on ding/policy/dt.py
> +    def get_d4rl_normalized_score(self, score, env_name):
where do we use this method

2023-07-31 12:33 UTC, PaParaZz1 commented on ding/policy/dt.py
> +            self.running_rtg = [self.rtg_target / self.rtg_scale for _ in range(self.eval_batch_size)]
remove `rtg_scale` argument

2023-07-31 12:33 UTC, PaParaZz1 commented on ding/policy/dt.py
> +            if self.cfg.env_type == 'atari':
polish this part

2023-07-31 12:33 UTC, PaParaZz1 commented on ding/policy/dt.py
> +        learn=dict(
remove sub level

2023-07-31 12:37 UTC, PaParaZz1 requested changes

2023-07-31 12:37 UTC, PaParaZz1 commented on ding/utils/data/dataset.py
> +        if 'hdf5' in dataset_path:
add env type comment

2023-07-31 12:37 UTC, PaParaZz1 commented on ding/utils/data/dataset.py
> +            print('max rtg is %d' % max(rtg))
use logging

2023-07-31 12:37 UTC, PaParaZz1 commented on ding/utils/data/dataset.py
> +class FixedReplayBuffer(object):
can we merge this class into the above class?

2023-07-31 12:37 UTC, PaParaZz1 commented on ding/utils/data/dataset.py
> +        from dopamine.replay_memory import circular_replay_buffer
can we remove requirement to `dopamine`

2023-08-04 09:51 UTC, AltmanD commented on dizoo/atari/entry/atari_dt_main.py
> +    # ding_init(cfg)
using 'DistributedWriter' cause different experiment log into one directory when use w&b

2023-08-19 12:36 UTC, PaParaZz1 approved these changes

2023-08-19 12:37 UTC, merged