feature(zc) : add plan diffuser
opendilab/DI-engine pull request #700
Opened 2023-08-08 08:26 UTC by Super1ce

## Description
add plan diffuser, add normalizer, add dataset

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2023-08-08 08:58 UTC, PaParaZz1 requested changes

2023-08-08 08:58 UTC, PaParaZz1 commented on ding/policy/command_mode_policy_instance.py
> +class EDACCommandModelPolicy(PDPolicy, DummyCommandModePolicy):
class name typo

2023-08-08 08:58 UTC, PaParaZz1 commented on dizoo/d4rl/entry/d4rl_dd_main.py
> +from ding.entry import serial_pipeline_offline
remove dd related codes

2023-08-08 08:58 UTC, PaParaZz1 commented on dizoo/d4rl/entry/d4rl_pd_main.py
> +    serial_pipeline_offline(config, seed=args.seed)
set max_train_iter

2023-08-08 08:58 UTC, PaParaZz1 commented on ding/policy/plan_diffuser.py
> +class PDPolicy(Policy):
add paper link

2023-08-10 07:16 UTC, Mossforest commented on ding/model/template/diffusion.py
> +def default_sample_fn(self, x, cond, t):
indent & arg 'self' -> should be model?

2023-08-11 04:42 UTC, Cloud-Pku commented on ding/model/template/diffusion.py
> +        self.register_buffer('sqrt_alphas_cumprod', torch.sqrt(alphas_cumprod))
where is the definition of the function "register_buffer"?

2023-08-11 04:42 UTC, Cloud-Pku commented on ding/model/template/diffusion.py
> +from typing import Union, List, Dict
I think you can add some unit tests to make the code easier to understand.
And it's convenient to check the rightness for each module.

2023-08-11 04:42 UTC, Cloud-Pku commented on ding/model/template/diffusion.py
> +    def q_posterior(self, x_start, x_t, t):
add comments and use cases

2023-08-27 12:07 UTC, PaParaZz1 requested changes

2023-08-27 12:07 UTC, PaParaZz1 commented on ding/torch_utils/network/diffusion.py
> +        if calc_energy:
why name `calc_energy` here

2023-08-27 12:07 UTC, PaParaZz1 commented on ding/torch_utils/network/diffusion.py
> +class MLPnet(nn.Module):
where is this module used?

2023-08-27 12:07 UTC, PaParaZz1 commented on ding/torch_utils/network/diffusion.py
> +class ARInvModel(nn.Module):
remove this dd model

2023-08-27 12:07 UTC, PaParaZz1 commented on ding/policy/plan_diffuser.py
> +    def _get_train_sample(self, data: list) -> Union[None, List[Any]]:
why not also set this method to pass?

2023-08-27 12:07 UTC, PaParaZz1 commented on ding/policy/plan_diffuser.py
> +            if id[i].item() in conds:
you can first use `id = id.tolist()`, then directly use this list rather than the `item` operation.

2023-08-27 12:07 UTC, PaParaZz1 commented on ding/policy/plan_diffuser.py
> +            else:
to refine this if-else branch, you can use `defaultdict(list)` here

2023-10-26 06:48 UTC, PaParaZz1 commented
This PR have been manually merged.

2023-10-26 06:48 UTC, closed without merging

2023-10-31 08:18 UTC, puyuan1996 commented on dizoo/d4rl/entry/d4rl_pd_main.py
> +    parser.add_argument('--config', '-c', type=str, default='hopper_expert_cql_config.py')
默认config应该改成plan diffuser相关的