fix(luyd):fix impala in lunarlander env
opendilab/DI-engine pull request #713
Opened 2023-08-23 08:04 UTC by AltmanD

Fix new pipeline impala in lunarlander env.

2023-09-13 08:08 UTC, PaParaZz1 requested changes

2023-09-13 08:08 UTC, PaParaZz1 commented on ding/data/buffer/deque_buffer.py
> +        self.sliced = sliced
add the new argument comment

2023-09-13 08:08 UTC, PaParaZz1 commented on ding/data/buffer/deque_buffer.py
> +                    start_indice = random.choice(range(max(1, len(seq_data))))
add some comments to explain reasons here

2023-09-13 08:08 UTC, PaParaZz1 commented on ding/data/buffer/deque_buffer.py
> +
add new unittest for this new argument

2023-09-13 08:08 UTC, PaParaZz1 commented on ding/example/impala.py
> +        task.use(termination_checker(max_env_step=15e5))
modify this value

2023-09-13 08:08 UTC, PaParaZz1 commented on ding/example/impala.py
> +        cfg.seed = 133
why modify seed here

2023-09-13 08:08 UTC, PaParaZz1 commented on ding/example/impala.py
> +        collector_env = BaseEnvManagerV2(
why not subprocess

2023-09-13 08:29 UTC, AltmanD commented
### Reward curve in Lunarlander, Pong, Spaceinvaders
#### Lunarlander:
![image](https://github.com/opendilab/DI-engine/assets/25995921/0d176992-e3ef-4277-ba40-c3b1546886ea)
#### Pong:
![image](https://github.com/opendilab/DI-engine/assets/25995921/64880916-6c6d-4c47-88c6-60d41f2d5863)
#### Spaceinvaders:
![image](https://github.com/opendilab/DI-engine/assets/25995921/6afc432f-7198-4bec-a8cf-02630478a7b0)

2023-09-14 03:17 UTC, PaParaZz1 approved these changes

2023-09-15 05:05 UTC, merged