polish(rjy): polish comments of qmix/pdqn/mavac
opendilab/DI-engine pull request #736
Opened 2023-10-07 10:11 UTC by nighood

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2023-10-10 03:50 UTC, puyuan1996 requested changes

2023-10-10 03:50 UTC, puyuan1996 commented on ding/model/template/mavac.py
> +        multi-agent, such as MAPPO. This model now supports discrete and continuous action space. \
增加mappo论文链接

2023-10-10 03:50 UTC, puyuan1996 commented on ding/model/template/mavac.py
> +            - agent_num (:obj:`int`): This parameter is temporarily reserved.
目前没有用到这个参数吗？讲清楚后续什么时候可能用到它

2023-10-10 03:50 UTC, puyuan1996 commented on ding/model/template/mavac.py
> +            - action_shape (:obj:`Union[int, SequenceType]`): Action space shape, such as 6 or [2, 3, 3].
也是for single agent的吧，可以写完整：Action space shape for single agent

2023-10-10 03:50 UTC, puyuan1996 commented on ding/model/template/mavac.py
> +            - mode (:obj:`str`): The forward mode, all the modes are defined in the beginning of this class.
指明mode有哪些可选项

2023-10-10 03:50 UTC, puyuan1996 commented on ding/model/template/mavac.py
> +            >>> assert actor_outputs['value'].shape == torch.Size([10, 8])
critic_outputs？

2023-10-10 03:50 UTC, puyuan1996 commented on ding/model/template/mavac.py
> +            MAVAC forward computation graph for critic part, input global observation tensor to predict state value.
这里应该写成：是使用input中的"global_state" tensor

2023-10-10 03:50 UTC, puyuan1996 commented on ding/model/template/mavac.py
> +            MAVAC forward computation graph for actor part, input observation tensor to predict action logit.
写详细一点，是用的input dict中的agent_state

2023-10-10 03:50 UTC, puyuan1996 commented on ding/model/template/mavac.py
> +            - x (:obj:`Dict`): The input observation and related info dict.
改成：- x (:obj:`Dict`): The input dict contains ``agent_state``,``global_state`` and other related info.

2023-10-10 03:50 UTC, puyuan1996 commented on ding/model/template/pdqn.py
> +        The neural network and computation graph of PDQN and MPDQN algorithms for parameterized action space. \
增加这2个算法的论文链接

2023-10-10 03:50 UTC, puyuan1996 commented on ding/model/template/pdqn.py
> +            - inputs (:obj:`torch.Tensor`): Observation inputs.
这里的inputs应该是指 - state (:obj:`torch.Tensor`): Observation inputs. 在这里注明一下

2023-10-10 03:50 UTC, puyuan1996 commented on ding/model/template/pdqn.py
> +        # 为什么这里encoder是同一个？
因为下面 compute_continuous 和 compute_discrete 在计算策略的cont和disc部分时，调用这里的encoder时，需要它的作用是一样的，都是对state的编码，因此用同一个实践上或许能加速特征的训练进程，与actor和critic共享前面部分的主干网络是类似的原理

2023-10-10 03:50 UTC, puyuan1996 commented on ding/model/template/qmix.py
> +        the weights of one layer of the Mixer network.
论文链接

2023-10-10 03:50 UTC, puyuan1996 commented on ding/model/template/qmix.py
>              Used to encoder global observation.
qmix算法流程中如果没有用到这个方法，就可以去掉哈

2023-10-16 09:18 UTC, PaParaZz1 approved these changes

2023-10-16 09:18 UTC, merged