polish(rjy): polish the comments of collate_fn/profiler_helper/metric
opendilab/DI-engine pull request #755
Opened 2023-12-02 11:19 UTC by nighood

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2023-12-06 07:59 UTC, kxzxvbk commented on ding/league/metric.py
> +            -ret (:obj:`Tuple[int, int]`): The new ratings for player A and player B, respectively.
There should be a blank between '-' and 'ret'

2023-12-06 08:00 UTC, kxzxvbk commented on ding/league/metric.py
> +            -ret(obj:`np.ndarray`): An array of new ratings for each player.
Also the blank

2023-12-06 08:03 UTC, kxzxvbk commented on ding/league/metric.py
> +            - PlayerRating: A player rating object with the specified mean, standard deviation, and Elo rating.
The return should also contain typing (:obj:`PlayerRating`)

2023-12-06 08:03 UTC, kxzxvbk commented on ding/league/metric.py
> +            - elo_init (:obj:int`): The initial Elo rating value for the player. If not provided, the default \
(:obj:`int`)

2023-12-06 08:04 UTC, kxzxvbk commented on ding/league/metric.py
> +            - PlayerRating: The updated rating for the team of players.
Type should be added.

2023-12-06 08:06 UTC, kxzxvbk commented on ding/utils/data/collate_fn.py
>  def ttorch_collate(x, json: bool = False, cat_1dim: bool = True):
The return type should be added, also for the comments below.

2023-12-06 08:07 UTC, kxzxvbk commented on ding/utils/data/collate_fn.py
>      def stack(data):
Why there is no comment for this function?

2023-12-06 08:09 UTC, kxzxvbk commented on ding/utils/profiler_helper.py
>      def profile(self, folder_path="./tmp"):
folder_path: str = "./tmp"

2023-12-11 09:26 UTC, PaParaZz1 requested changes

2023-12-11 09:26 UTC, PaParaZz1 commented on ding/utils/data/collate_fn.py
> +    """
add an example for this function

2023-12-11 09:26 UTC, PaParaZz1 commented on ding/utils/profiler_helper.py
> +    def write_profile(self, pr, folder_path: str):
add typing lint for `pr`

2023-12-11 09:26 UTC, PaParaZz1 commented on ding/utils/profiler_helper.py
> +            - folder_path (str, optional): The path of the folder where the profiling files will be saved. \
modify typing lint

2023-12-11 09:26 UTC, PaParaZz1 commented on ding/league/metric.py
> -        t1_elo, t2_elo = t1.elo, t2.elo
why delete these codes

2023-12-14 07:49 UTC, merged