doc(rjy): polish d4pg/ppg/qrdqn policy doc
opendilab/DI-engine pull request #762
Opened 2024-01-08 07:16 UTC by nighood

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2024-01-08 12:22 UTC, PaParaZz1 commented on ding/policy/qrdqn.py
> +        the return value, and then use the quantile to calculate the quantile loss.
add paper link

2024-01-15 13:04 UTC, zjowowen commented on ding/policy/d4pg.py
> +            Return this algorithm default neural network model setting for demonstration. ``__init__`` method will \
"Return this algorithm default neural network model setting for demonstration." -> "Return the default neural network model class for D4PGPolicy."

2024-01-15 13:11 UTC, zjowowen commented on ding/policy/d4pg.py
> +                keys. Additionally, loss_dict also contain other keys, which are mainly used for monitoring and \
"Additionally, loss_dict also contain other keys, which are mainly used for monitoring and" -> "Additionally, loss_dict also contains other keys, which is mainly used for monitoring and"

2024-01-15 13:15 UTC, zjowowen commented on ding/policy/ppg.py
> +    Arguments:
Put Arguments into the notation of def __init__ function.

2024-01-15 13:16 UTC, zjowowen commented on ding/policy/ppg.py
> +        data (:obj:`dict`): A dictionary containing the experience data, where the keys represent the data types \
"data (:obj:`dict`)" -> "- data (:obj:`dict`)"

2024-01-15 13:24 UTC, zjowowen commented on ding/policy/ppg.py
> +        Policy class of PPG algorithm with off-policy training mode. We implement off-policy PPG with two buffers \
"We implement off-policy PPG with two buffers with different data use constraint (max_use), which policy buffer offers data for policy phase while value buffer provides auxiliary phase's data." -> "Off-policy PPG contains two different data max_use buffers.  The policy buffer offers data for policy phase , while the value buffer provides auxiliary phase's data."

2024-01-15 13:31 UTC, zjowowen commented on ding/policy/ppg.py
> +                dict is the name of data items and the value is the corresponding data. Usually, the value is \
"Usually, the value is ..." ->
"Usually, the class type of value is either torch.Tensor or np.ndarray, or a dict/list containing either torch.Tensor or np.ndarray items"

2024-01-16 06:15 UTC, PaParaZz1 requested changes

2024-01-16 06:15 UTC, PaParaZz1 commented on ding/policy/d4pg.py
> +                containing at least the "actor lr", "critic lr", "different losses", "q_value", "action", "priority", \
cur_lr_actor

2024-01-16 06:15 UTC, PaParaZz1 commented on ding/policy/d4pg.py
>      def _forward_learn(self, data: dict) -> Dict[str, Any]:
`data: List[Dict[str, Any]]`  refer to dqn/ddpg

2024-01-16 06:15 UTC, PaParaZz1 commented on ding/policy/qrdqn.py
> +            - data (:obj:`dict`): input data used for policy forward, including the \
Input

2024-01-16 06:15 UTC, PaParaZz1 commented on ding/policy/ppg.py
> +            Initialize the collect mode of policy, including related attributes and modules. For PPO, it contains the \
for PPG

2024-01-16 06:15 UTC, PaParaZz1 commented on ding/policy/ppg.py
> +               Process and pack one timestep transition data into a dict, which can be directly used for training and \
wrong indent

2024-01-16 06:15 UTC, PaParaZz1 commented on ding/policy/ppg.py
> +                as input. For PPG, it contains the state value, action and the logit of the action.
there should be some indents

2024-01-16 06:15 UTC, PaParaZz1 commented on ding/policy/ppg.py
>      def _get_train_sample(self, data: list) -> Union[None, List[Any]]:
typing lint

2024-01-22 04:44 UTC, PaParaZz1 approved these changes

2024-01-22 04:44 UTC, merged