env(rjy): add ising model env
opendilab/DI-engine pull request #782
Opened 2024-03-12 10:55 UTC by nighood

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2024-04-07 04:27 UTC, PaParaZz1 requested changes

2024-04-08 06:03 UTC, puyuan1996 requested changes

2024-04-08 06:03 UTC, puyuan1996 commented on dizoo/ising_env/envs/ising_model_env.py
> +#     sys.path.append(ising_model_dir)
删除无用注释

2024-04-08 06:03 UTC, puyuan1996 commented on dizoo/ising_env/envs/ising_model_env.py
> +class IsingModelEnv(BaseEnv):
写一下overview，介绍ising_model的简介，agent目标，MDP定义，参考论文链接等

2024-04-17 05:46 UTC, nighood commented on ding/rl_utils/td.py
> +    if len(action.shape) == 1 or len(action.shape) < len(q.shape):  # single agent case
we need to unsqueeze action and q to make them have the same shape
e.g. single agent case: action is [B, ] and q is [B, ]
e.g. multi agent case: action is [B, agent_num] and q is [B, agent_num, action_shape]

2024-04-19 11:26 UTC, PaParaZz1 approved these changes

2024-04-19 11:26 UTC, PaParaZz1 commented on ding/model/template/q_learning.py
> +        init_bias: Optional[float] = None,
You need to also update the comments of `Arguments`

2024-04-19 11:26 UTC, PaParaZz1 commented on ding/policy/common_utils.py
> +            data['reward'] = reward.transpose(0, 2).transpose(1, 2).contiguous()
use `permute` rather than two `transpose` operations

2024-04-19 11:26 UTC, PaParaZz1 commented on ding/policy/common_utils.py
> +            raise ValueError("The 'reward' tensor must be either 2D or 3D.")
You should add the ndim information in the error information

2024-04-19 11:26 UTC, PaParaZz1 commented on dizoo/ising_env/config/ising_mfq_config.py
> +    set_pkg_seed(seed)
why call this function, which is already called inside `serial_pipeline`

2024-04-22 09:28 UTC, PaParaZz1 approved these changes

2024-04-23 05:22 UTC, PaParaZz1 approved these changes

2024-04-23 05:23 UTC, merged