First commit for taxi
opendilab/DI-engine pull request #799
Opened 2024-05-29 05:13 UTC by ruiheng123

## Description

## Related Issue

## TODO

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2024-05-29 05:32 UTC, PaParaZz1 requested changes

2024-05-29 05:32 UTC, PaParaZz1 commented on dizoo/taxi/config/__init__.py
> +from .taxi_dqn_config import main_config, create_config
you should not upload the binary `pyc` file into GitHub

2024-05-29 05:32 UTC, PaParaZz1 commented on dizoo/taxi/envs/__init__.py
> +from .taxi_env import TaxiV3Env
TaxiEnv

2024-05-29 05:32 UTC, PaParaZz1 commented on dizoo/taxi/envs/taxi_env.py
> +import copy
please polish the import sequence according to the doc [here](https://di-engine-docs.readthedocs.io/zh-cn/latest/21_code_style/index.html#reasonable-import-order)

2024-05-29 05:32 UTC, PaParaZz1 commented on dizoo/taxi/envs/taxi_env.py
> +        #^ 该部分为初始化定义，需要有的
use English comment

2024-05-29 05:32 UTC, PaParaZz1 commented on dizoo/taxi/envs/taxi_env.py
> +        self._cfg = EasyDict(
use the implementation like `default_config` in other previous environment in dizoo

2024-05-29 05:32 UTC, PaParaZz1 commented on dizoo/taxi/envs/taxi_env.py
> +import copy
polish the code style of this file with our `format.sh`, for example
```shell
./format.sh ./dizoo/taxi/envs/taxi_env.py
```

2024-05-29 05:32 UTC, PaParaZz1 commented on dizoo/taxi/envs/taxi_env.py
> +        self._observation_space = gym.spaces.Box(low=0, high=1, shape=(500, ), dtype=np.float32)
why do you define this member variable twice?

2024-05-29 05:32 UTC, PaParaZz1 commented on dizoo/taxi/envs/taxi_env.py
> +        self._save_replay_bool = False
simplify to `self._save_replay`

2024-05-29 05:32 UTC, PaParaZz1 commented on dizoo/taxi/envs/test_taxi_env.py
> +                print(f"你本次的Timestep是：{timestep}")
use English

2024-05-29 05:32 UTC, PaParaZz1 commented on dizoo/taxi/envs/test_taxi_env.py
> +#& 为了测试一下可视化的结果，我还这么测试了一个definite的序列，就是能接到乘客且对号入座甩客的actions
remove commented code if it is only used for the local debug operation

2024-05-29 05:32 UTC, PaParaZz1 commented on dizoo/taxi/config/__init__.py
> +from .taxi_dqn_config import main_config, create_config
update the env table in readme

2024-05-30 07:24 UTC, zjowowen commented on dizoo/taxi/envs/taxi_env.py
> +        """
Polish argument list as the format in https://github.com/opendilab/DI-engine/blob/main/ding/model/common/encoder.py.

2024-05-30 07:58 UTC, PaParaZz1 approved these changes

2024-05-30 08:14 UTC, merged